import resImg from './imgs/restaurant img.jpg';

function generateHomePage() {
    const content = document.querySelector('#content');
    content.innerHTML = '';
    const resName = document.createElement('div');
    const summary = document.createElement('div');
    const hours = document.createElement('div');
    const location = document.createElement('div');
    const hoursHead = document.createElement('h2');
    const locationHead = document.createElement('h2');
    const sunday = document.createElement('p');
    const monday = document.createElement('p');
    const tuesday = document.createElement('p');
    const wednesday = document.createElement('p');
    const thursday = document.createElement('p');
    const friday = document.createElement('p');
    const saturday = document.createElement('p');
    const springMountain = document.createElement('p');
    const rainbow = document.createElement('p');
    const centennial = document.createElement('p');
    const img = new Image();
    resName.classList.add('res-name');
    summary.classList.add('summary');
    hours.classList.add('hours');
    location.classList.add('location');
    img.src = resImg;
    resName.textContent = 'Karma Curry';
    summary.textContent = 'Here at Karma Curry, we serve the best Japanese Curry in Las Vegas. We started as a small family owned business and have grew into a hotspot known all over town. We promise you won\'t be disappointed!';
    hoursHead.textContent = 'Hours:';
    sunday.textContent = 'Sunday: 11AM - 11PM';
    monday.textContent = 'Monday: 11AM - 11PM';
    tuesday.textContent = 'Tuesday: 11AM - 11PM';
    wednesday.textContent = 'Wednesday: 11AM - 11PM';
    thursday.textContent = 'Thursday: 11AM - 11PM';
    friday.textContent = 'Friday: 11AM - 12AM';
    saturday.textContent = 'Saturday: 11AM - 12AM';
    locationHead.textContent = 'Locations:';
    springMountain.textContent = 'Spring Mountain: 5020 Spring Mountain Rd #1, Las Vegas, NV 89146';
    rainbow.textContent = 'Rainbow: 7835 S Rainbow Blvd #9, Las Vegas, NV 89139';
    centennial.textContent = 'Centennial: 225 W Centennial Pkwy, North Las Vegas, NV 89084';
    hours.appendChild(hoursHead);
    hours.appendChild(sunday);
    hours.appendChild(monday);
    hours.appendChild(tuesday);
    hours.appendChild(wednesday);
    hours.appendChild(thursday);
    hours.appendChild(friday);
    hours.appendChild(saturday);
    location.appendChild(locationHead);
    location.appendChild(springMountain);
    location.appendChild(rainbow);
    location.appendChild(centennial);
    content.appendChild(resName);
    content.appendChild(img);
    content.appendChild(summary);
    content.appendChild(hours);
    content.appendChild(location);
}

export default generateHomePage;